module.exports = {
  GET_CATEGORIES: 'GET_CATEGORIES',
  ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
  ADD_NEW_SECTION: 'ADD_NEW_SECTION',
  DELETE_SECTION: 'DELETE_SECTION',
  UPDATE_SECTION: 'UPDATE_SECTION',
  SORT_CATEGORY_SECTIONS: 'SORT_CATEGORY_SECTIONS',
  SORT_SECTION_ITEMS: 'SORT_SECTION_ITEMS',
  SORT_CATEGORIES: 'SORT_CATEGORIES',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  UPDATE_COMPONENTS: 'UPDATE_COMPONENTS',
  CLOSE_ALL_NEW_SECTION_COMPONENTS: 'CLOSE_ALL_NEW_SECTION_COMPONENTS',
  ADD_NEW_SECTION_COMPONENT: 'ADD_NEW_SECTION_COMPONENT',
  GET_COMPONENTS: 'GET_COMPONENTS',
  GET_NEW_SECTION_COMPONENT: 'GET_NEW_SECTION_COMPONENT'
};
